#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

PROJECT_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
DEPLOY_DIR="$PROJECT_ROOT/implementation/attic"
ENV_FILE="$DEPLOY_DIR/.env"
COMPOSE_FILE="$DEPLOY_DIR/compose.example.yaml"

compose() {
  docker compose --project-directory "$DEPLOY_DIR" -f "$COMPOSE_FILE" "$@"
}

usable_value() {
  local value
  value=$(_existing "$1" || true)
  [[ "$value" == replace-* ]] && value=""
  printf '%s' "$value"
}

root_openai_key() {
  local key value=""
  [[ -f "$PROJECT_ROOT/.env" ]] || return 0
  while IFS='=' read -r key value; do
    [[ "$key" == "OPENAI_API_KEY" ]] || continue
    value="${value%$'\r'}"
    if [[ "$value" == \"*\" && "$value" == *\" ]]; then
      value="${value:1:${#value}-2}"
    elif [[ "$value" == \'*\' && "$value" == *\' ]]; then
      value="${value:1:${#value}-2}"
    fi
    printf '%s' "$value"
    return 0
  done < "$PROJECT_ROOT/.env"
}

generate_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    LC_ALL=C od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
  fi
}

banner "Attic launcher"

stage "Check this host"
say "Attic will use your existing PostgreSQL server and Docker Compose."
for command_name in docker curl; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    printf '  %s✗ missing required command:%s %s\n' "$RED" "$RESET" "$command_name" >&2
    exit 1
  fi
done
if ! docker compose version >/dev/null 2>&1; then
  printf '  %s✗ Docker Compose v2 is required.%s\n' "$RED" "$RESET" >&2
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  printf '  %s✗ Docker is not reachable by this user.%s\n' "$RED" "$RESET" >&2
  exit 1
fi
[[ -f "$COMPOSE_FILE" && -f "$DEPLOY_DIR/.env.example" ]] || {
  printf '  %s✗ deployment files are missing.%s\n' "$RED" "$RESET" >&2
  exit 1
}
say "Docker, Compose, and the Attic deployment files are ready."

stage "Configure Attic"
say "Values are saved to implementation/attic/.env with owner-only permissions."
note "For PostgreSQL on this Docker host, use host.docker.internal as the hostname."
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

DATABASE_URL=$(usable_value DATABASE_URL)
if [[ -z "$DATABASE_URL" ]]; then
  ask_secret DATABASE_URL "PostgreSQL connection URL:"
fi
[[ -n "$DATABASE_URL" ]] || { warn "DATABASE_URL cannot be empty."; exit 1; }

PUBLIC_BASE_URL=$(usable_value PUBLIC_BASE_URL)
if [[ -z "$PUBLIC_BASE_URL" ]]; then
  PUBLIC_BASE_URL="http://127.0.0.1:8080"
  write_env PUBLIC_BASE_URL "$PUBLIC_BASE_URL"
fi
ask PUBLIC_BASE_URL "Public base URL:"
[[ -n "$PUBLIC_BASE_URL" ]] || { warn "PUBLIC_BASE_URL cannot be empty."; exit 1; }

BEARER_TOKEN=$(usable_value BEARER_TOKEN)
if [[ -z "$BEARER_TOKEN" ]]; then
  BEARER_TOKEN=$(generate_token)
  say "Generated a private owner bearer token."
fi

AI_BASE_URL=$(usable_value AI_BASE_URL)
[[ -n "$AI_BASE_URL" ]] || AI_BASE_URL="https://api.openai.com/v1"
AI_MODEL=$(usable_value AI_MODEL)
[[ -n "$AI_MODEL" ]] || AI_MODEL="gpt-5.6-luna"
AI_PROVIDER=$(usable_value AI_PROVIDER)
[[ -n "$AI_PROVIDER" ]] || AI_PROVIDER="api"
case "$AI_PROVIDER" in
  api)
    AI_API_KEY=$(usable_value AI_API_KEY)
    if [[ -z "$AI_API_KEY" ]]; then
      AI_API_KEY=$(root_openai_key)
      [[ -n "$AI_API_KEY" ]] && say "Reused OPENAI_API_KEY from the ignored root .env."
    fi
    if [[ -z "$AI_API_KEY" ]]; then
      ask_secret AI_API_KEY "OpenAI-compatible API key:"
    fi
    [[ -n "$AI_API_KEY" ]] || { warn "AI_API_KEY cannot be empty."; exit 1; }
    write_env AI_API_KEY "$AI_API_KEY"
    ;;
  chatgpt)
    say "Using direct ChatGPT subscription authentication."
    note "After the build, connect your account with the documented login-chatgpt command."
    ;;
  *) warn "AI_PROVIDER must be api or chatgpt."; exit 1 ;;
esac
write_env AI_PROVIDER "$AI_PROVIDER"

write_env DATABASE_URL "$DATABASE_URL"
write_env PUBLIC_BASE_URL "$PUBLIC_BASE_URL"
write_env BEARER_TOKEN "$BEARER_TOKEN"
write_env AI_BASE_URL "$AI_BASE_URL"
write_env AI_MODEL "$AI_MODEL"
write_env SMTP_ENABLED "false"
chmod 600 "$ENV_FILE"
say "The AI model is $AI_MODEL (provider: $AI_PROVIDER)."

stage "Build and launch"
say "Compose will build Attic, apply migrations, and start the worker."
if ! confirm "Build and start Attic now?"; then
  warn "Launch cancelled; configuration remains saved."
  exit 0
fi
compose config --quiet
compose up -d --build

say "Waiting up to 90 seconds for PostgreSQL-backed readiness..."
deadline=$((SECONDS + 90))
until curl -fsS http://127.0.0.1:8080/health/ready >/dev/null 2>&1; do
  if (( SECONDS >= deadline )); then
    warn "Attic did not become ready. Recent logs follow."
    compose logs --tail 80 attic
    exit 1
  fi
  sleep 2
done

finish
printf '  %s✓ Attic is ready%s at http://127.0.0.1:8080\n' "$GREEN" "$RESET"
printf '  Health: http://127.0.0.1:8080/health/ready\n'
printf '  API:    http://127.0.0.1:8080/api/v1/jobs\n'
printf '  Config: implementation/attic/.env\n'
printf '  Logs:   docker compose -f implementation/attic/compose.example.yaml logs -f attic\n\n'
